### ISSUE TITLE
no such subcommand: `generate`

### ISSUE THREAD

**Issue by ithinco** [terra-money/terrain#27]
![image](https://user-images.githubusercontent.com/1669761/163292436-c9f7b71e-bd9f-41f1-93d5-c38eb06d59a5.png)
mac m1 chip
rust installed

**Comment by emidev98** [comment]
Hello @ithinco, 

Have you followed all this steps https://github.com/terra-money/terrain#setup-rust? Because I have a feeling that `cargo install cargo-generate --features vendored-openssl` is missing. Could you execute them again and confirm please?

**Comment by emidev98** [comment]
@ithinco did it worked?

**Comment by ithinco** [comment]
Thanks, it works. Now I encounter another error when `npm run start` in frontend folder, I didn't deploy the contract, just want a try.

```
Failed to compile.

./src/contract/address.js
Module not found: Can't resolve '../refs.terrain.json' in '/Users/admin/Desktop/mine/terra-demo/frontend/src/contract'
```

**Comment by emidev98** [comment]
Its a common error have you deployed the application before trying to start the frontend? 
Because in order to run the frontend you must have a **refs.terrain.json** file inside the frontend **src** folder. 
![image](https://user-images.githubusercontent.com/49301655/163569768-8128e225-f822-40d0-a6c3-e3f75bcd860a.png)

**Comment by ithinco** [comment]
The reason is because `terrain sync-refs` command missing in https://docs.terra.money/docs/develop/dapp/quick-start/using-terrain-testnet.html
